"use client";
import {useEffect,useMemo,useRef,useState} from "react"; import {createClient} from "@/lib/supabase/client";
const nav=["Dashboard","Inbox","Radar","Kanban","Clientes","Follow-ups","Ligações","Campanhas","Automações","Respostas rápidas","Equipe","Auditoria","IA","Configurações"];
const products=["INSS","Público","Privado","Cartão consignado","Cartão benefício","Crédito pessoal","Seguro médico","Seguro residencial","Seguro funeral","Energia solar","FGTS","Crédito do Trabalhador/CLT","SIAPE","Militar"];
const stages=["Novo","Contato","Proposta","Negociação","Fechado","Perdido"];
export default function Deskcomm({userId}:{userId:string}){const[v,setV]=useState("Dashboard"),[q,setQ]=useState(""),[dark,setDark]=useState(false),[role,setRole]=useState("operator"),[d,setD]=useState<any>({leads:[],conversations:[],followups:[],calls:[]}),[toast,setToast]=useState(""),[sel,setSel]=useState(""),[msgs,setMsgs]=useState<any[]>([]),[txt,setTxt]=useState(""),[modal,setModal]=useState(false),[busy,setBusy]=useState(false),[importing,setImporting]=useState(false),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState("");const file=useRef<HTMLInputElement>(null);
const load=async()=>{setLoading(true);setLoadError("");try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),10000);const r=await fetch("/api/crm?resource=dashboard",{cache:"no-store",credentials:"same-origin",signal:controller.signal});clearTimeout(timer);if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.error||`Erro ${r.status}`)}const json=await r.json();setD(json);setRole(json.role||"operator")}catch(e){setLoadError(e instanceof Error?e.message:"Falha ao carregar o CRM")}finally{setLoading(false)}};useEffect(()=>{load()},[]);
const post=async(resource:string,data:any)=>{setBusy(true);const r=await fetch("/api/crm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resource,data})});const j=await r.json().catch(()=>({}));setBusy(false);setToast(r.ok?"Operação concluída":j.error||"Operação recusada");if(r.ok)load();return r.ok};
const select=async(id:string)=>{setSel(id);const r=await fetch("/api/crm?resource=messages&conversation_id="+id);if(r.ok)setMsgs((await r.json()).messages||[])};const active=d.conversations.find((x:any)=>x.id===sel)||d.conversations[0];
const filtered=useMemo(()=>d.leads.filter((x:any)=>(x.contact.name+" "+x.contact.phone+" "+x.product).toLowerCase().includes(q.toLowerCase())),[d.leads,q]);
async function imp(){const fs=Array.from(file.current?.files||[]);if(!fs.length)return;setImporting(true);const fd=new FormData();fs.forEach(f=>fd.append("files",f));const r=await fetch("/api/import",{method:"POST",body:fd});const j=await r.json();setImporting(false);setToast(r.ok?"Importados "+j.imported+" leads em "+(j.files?.length||fs.length)+" arquivo(s)":j.error||"Falha");if(r.ok)load();if(file.current)file.current.value=""}
async function logout(){await createClient().auth.signOut();location.href="/login"}
return <div className={dark?"app dark":"app"}><aside><div className="brand">A&K <em>Deskcomm</em></div><div className="org">SOLUÇÕES FINANCEIRAS</div>{nav.map(x=><button key={x} className={v===x?"nav active":"nav"} onClick={()=>setV(x)}><b>{x==="Dashboard"?"⌂":x==="Inbox"?"◉":x==="Ligações"?"☎":"•"}</b>{x}</button>)}<div className="asideBottom"><button className="theme" onClick={()=>setDark(!dark)}>◐ Tema</button><button className="theme" onClick={logout}>↪ Sair</button></div></aside>
<main><header><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar cliente, telefone ou produto..."/><span className="online">● Operação protegida</span><div className="avatar">AK</div><div><b>{role==="owner"?"Administrador":role==="admin"?"Administrador":role==="manager"?"Gerente":"Operador"}</b><small>{userId.slice(0,8)}…</small></div></header><section>
{v==="Dashboard"&&<><Head title="Visão geral" sub="A&K Soluções Financeiras" action={<button className="btn primary" onClick={()=>setV("Inbox")}>Abrir Inbox</button>}/><div className="metrics"><Metric a="Leads ativos" b={String(d.leads.filter((x:any)=>!x.contact.blocked).length)} c="Banco real"/><Metric a="Conversas" b={String(d.conversations.length)} c="Fila"/><Metric a="Follow-ups" b={String(d.followups.length)} c="Pendentes"/><Metric a="Ligações" b={String(d.calls.length)} c="Histórico"/></div><div className="cols"><List title="Pipeline" rows={d.leads.slice(0,8).map((x:any)=>x.contact.name+" · "+x.product+" · "+x.stage)}/><div className="card"><h3>Segurança</h3><div className="row">Auth + SSR <span className="pill green">Ativo</span></div><div className="row">RLS multi-tenant <span className="pill green">Ativo</span></div><div className="row">Auditoria append-only <span className="pill green">Ativo</span></div><div className="row">IA/RAG <span className="pill">Estrutura</span></div><div className="notice">Phone Link fica somente no projeto ak-call-center.</div></div></div></>}
{v==="Inbox"&&<><Head title="Inbox" sub="Atendimento + Customer 360"/><div className="inbox"><div className="list">{d.conversations.map((c:any)=><button className={sel===c.id?"conv active":"conv"} key={c.id} onClick={()=>select(c.id)}><b>{c.contact.name}</b><small>{c.channel} · {c.status}</small></button>)}</div><div className="chat">{active?<><div className="chathead"><b>{active.contact.name}</b><small>{active.contact.phone}</small></div><div className="messages">{msgs.map(m=><div className={"bubble "+(m.direction==="outbound"?"agent":"")} key={m.id}>{m.body}<small>{new Date(m.created_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</small></div>)}</div><div className="composer"><textarea value={txt} onChange={e=>setTxt(e.target.value)}/><button className="btn primary" onClick={()=>txt.trim()&&post("message",{conversation_id:active.id,text:txt.trim()}).then(ok=>{if(ok){setTxt("");select(active.id)}})}>Registrar</button></div></>:<div className="empty">Selecione uma conversa.</div>}</div><div className="detail"><h3>Customer 360</h3>{active?<><div className="bigavatar">{active.contact.name.slice(0,2)}</div><b>{active.contact.name}</b><small>{active.contact.phone}</small><hr/><span className="tag">Lead</span><span className="tag">A&K</span></>:<small>Nenhum contato.</small>}</div></div></>}
{v==="Radar"&&<><Head title="Radar" sub="Prioridades, Não Ligar e Não Me Perturbe"/><div className="card">{filtered.map((x:any)=><div className="row" key={x.id}><div><b>{x.contact.name}</b><small>{x.contact.phone} · {x.product}</small></div>{x.contact.blocked?<span className="pill red">Bloqueado</span>:<button className="btn" onClick={()=>post("block",{phone:x.contact.phone,reason:"nao_ligar"})}>Não ligar</button>}</div>)}</div></>}
{v==="Kanban"&&<><Head title="Kanban" sub="Pipeline comercial" action={<button className="btn primary" onClick={()=>setModal(true)}>+ Novo lead</button>}/><div className="kanban">{stages.map(s=><div className="column" key={s}><h3>{s}<span>{filtered.filter((x:any)=>x.stage===s).length}</span></h3>{filtered.filter((x:any)=>x.stage===s).map((x:any)=><div className="lead" key={x.id}><b>{x.contact.name}</b><small>{x.contact.phone}</small><span className="tag">{x.product}</span><select value={s} onChange={e=>post("lead_update",{id:x.id,stage:e.target.value})}>{stages.map(y=><option key={y}>{y}</option>)}</select></div>)}</div>)}</div></>}
{v==="Clientes"&&<><Head title="Clientes" sub="Base + importação CSV/XLS/XLSX/ODS" action={<><button className="btn" onClick={()=>file.current?.click()}>{importing?"Importando...":"Importar 1 ou várias planilhas"}</button><button className="btn primary" onClick={()=>setModal(true)}>+ Novo</button></>}/><div className="card tablewrap"><table><thead><tr><th>Cliente</th><th>Telefone</th><th>Produto</th><th>Etapa</th><th>Status</th></tr></thead><tbody>{filtered.map((x:any)=><tr key={x.id}><td>{x.contact.name}</td><td>{x.contact.phone}</td><td>{x.product}</td><td>{x.stage}</td><td><span className={x.contact.blocked?"pill red":"pill green"}>{x.contact.blocked?"Bloqueado":"Ativo"}</span></td></tr>)}</tbody></table></div></>}
{v==="Follow-ups"&&<><Head title="Follow-ups" sub="Retornos e tarefas" action={<button className="btn primary" disabled={!d.leads[0]} onClick={()=>d.leads[0]&&post("followup",{lead_id:d.leads[0].id,title:"Retorno de teste",due_at:new Date(Date.now()+3600000).toISOString()})}>+ Testar</button>}/><List title="Pendentes" rows={d.followups.map((x:any)=>x.title+" · "+new Date(x.due_at).toLocaleString("pt-BR"))}/></>}
{v==="Ligações"&&<><Head title="Ligações" sub="Histórico do CRM; Phone Link permanece na discadora" action={<button className="btn primary" disabled={!d.leads[0]} onClick={()=>d.leads[0]&&post("call",{lead_id:d.leads[0].id,phone:d.leads[0].contact.phone,result:"Atendeu",duration_seconds:60})}>Simular ligação</button>}/><List title="Histórico" rows={d.calls.map((x:any)=>x.phone+" · "+x.result+" · "+x.duration_seconds+"s")}/></>}
{v==="Campanhas"&&<><Head title="Campanhas" sub="Campanhas comerciais" action={<button className="btn primary" onClick={()=>post("campaign",{name:"Campanha de teste",product:"INSS"})}>+ Criar</button>}/><div className="card"><p>Produtos: {products.join(" · ")}</p><div className="notice">Disparos externos exigem canal autenticado e consentimento.</div></div></>}
{v==="Automações"&&<><Head title="Automações" sub="Regras do Deskcomm"/><div className="card"><div className="row">Novo lead → atribuir operador <span className="pill green">Ativo</span></div><div className="row">STOP/NPD → bloquear <span className="pill green">Ativo</span></div><div className="row">Resposta → criar follow-up <span className="pill">Estrutura</span></div></div></>}
{v==="Respostas rápidas"&&<><Head title="Respostas rápidas" sub="Biblioteca operacional"/><List title="Modelos" rows={["Boas-vindas","Simulação","Documentos","Retorno"]}/></>}
{v==="Equipe"&&<Module resource="team" title="Equipe" sub="RBAC por organização"/>}
{v==="Auditoria"&&<Module resource="audit" title="Auditoria" sub="Trilha append-only no Supabase"/>}
{v==="IA"&&<><Head title="IA / RAG" sub="Agentes, skills, memória e conhecimento"/><div className="cols"><div className="card"><h3>Agentes</h3><p>Provider, modelo, prompt e orçamento por organização.</p><span className="pill green">Banco pronto</span></div><div className="card"><h3>RAG</h3><p>Documentos + chunks vetoriais + RPC de busca.</p><span className="pill green">pgvector</span></div></div></>}
{v==="Configurações"&&<><Head title="Configurações" sub="Segurança e integração futura"/><div className="cols"><div className="card"><h3>Segurança</h3><div className="row">RLS <span className="pill green">Obrigatório</span></div><div className="row">Service role <span className="pill green">Servidor</span></div><div className="row">API cache <span className="pill green">no-store</span></div></div><div className="card"><h3>Discadora</h3><p>Integração futura por API autenticada. Nenhuma chamada é enviada agora.</p></div></div></>}
</section></main><input ref={file} hidden multiple type="file" accept=".csv,.xls,.xlsx,.ods" onChange={imp}/>{modal&&<LeadModal busy={busy} close={()=>setModal(false)} save={async(x:any)=>{if(await post("lead",x))setModal(false)}}/>}{toast&&<div className="toast">✓ {toast}</div>}</div>}
function Head({title,sub,action}:{title:string;sub:string;action?:React.ReactNode}){return <div className="title"><div><h1>{title}</h1><p>{sub}</p></div>{action}</div>}
function Metric({a,b,c}:{a:string;b:string;c:string}){return <div className="card metric"><small>{a}</small><strong>{b}</strong><span>{c}</span></div>}
function List({title,rows}:{title:string;rows:string[]}){return <div className="card"><h3>{title}</h3>{rows.length?rows.map((x,i)=><div className="row" key={i}>{x}</div>):<div className="empty">Nenhum registro.</div>}</div>}
function Module({resource,title,sub}:{resource:string;title:string;sub:string}){const[r,setR]=useState<any[]>([]);useEffect(()=>{fetch("/api/crm?resource="+resource).then(x=>x.json()).then(j=>setR(j[resource]||j.team||j.audit||[]))},[resource]);return <><Head title={title} sub={sub}/><List title="Registros" rows={r.map((x:any)=>x.name||x.action||x.user_id||String(x.id))}/></>}
function LeadModal({close,save,busy}:{close:()=>void;save:(x:any)=>void;busy:boolean}){const[n,setN]=useState(""),[p,setP]=useState(""),[prod,setProd]=useState(products[0]);return <div className="modal"><form className="modalbox" onSubmit={e=>{e.preventDefault();save({name:n,phone:p,product:prod})}}><div className="title"><h2>Novo lead</h2><button type="button" className="btn" onClick={close}>Fechar</button></div><label>Nome<input value={n} onChange={e=>setN(e.target.value)} required/></label><label>Telefone<input value={p} onChange={e=>setP(e.target.value)} required/></label><label>Produto<select value={prod} onChange={e=>setProd(e.target.value)}>{products.map(x=><option key={x}>{x}</option>)}</select></label><button className="btn primary wide" disabled={busy}>Salvar</button></form></div>}
