'use client';
import {useEffect,useMemo,useState} from 'react';

type Lead={id:number;name:string;phone:string;product:string;stage:string;owner:string;blocked:boolean};
type Msg={id:number;from:'client'|'agent';text:string;time:string};
type Conv={id:number;name:string;channel:string;preview:string;messages:Msg[]};
const stages=['Novo','Contato','Proposta','Negociação'];
const nav=[['⌂','Dashboard'],['◉','Inbox'],['◈','Radar'],['▦','Kanban'],['◎','Clientes'],['✓','Follow-ups'],['☎','Ligações'],['▤','Campanhas'],['⚙','Automações'],['⚡','Respostas rápidas'],['♙','Equipe'],['◌','Auditoria'],['☷','Configurações']];
const seedLeads:Lead[]=[
{id:1,name:'Maria Oliveira',phone:'(79) 99911-2233',product:'INSS',stage:'Novo',owner:'Adriel',blocked:false},
{id:2,name:'João Santos',phone:'(79) 98877-1144',product:'CLT',stage:'Contato',owner:'Camila',blocked:false},
{id:3,name:'Ana Souza',phone:'(79) 99771-6655',product:'SIAPE',stage:'Proposta',owner:'Adriel',blocked:false},
{id:4,name:'Carlos Lima',phone:'(79) 99123-7766',product:'FGTS',stage:'Negociação',owner:'Rafael',blocked:false},
{id:5,name:'Paulo Reis',phone:'(79) 99666-5511',product:'Benefício',stage:'Novo',owner:'Camila',blocked:true}];
const seedConvs:Conv[]=[
{id:1,name:'Maria Oliveira',channel:'WhatsApp',preview:'Pode fazer uma simulação?',messages:[{id:1,from:'client',text:'Bom dia! Vi o anúncio de cartão benefício.',time:'08:40'},{id:2,from:'agent',text:'Bom dia, Maria! Posso verificar as opções.',time:'08:41'},{id:3,from:'client',text:'Pode fazer uma simulação?',time:'08:42'}]},
{id:2,name:'João Santos',channel:'WhatsApp',preview:'Tenho interesse no crédito CLT',messages:[{id:4,from:'client',text:'Tenho interesse no crédito CLT',time:'08:17'}]},
{id:3,name:'Ana Souza',channel:'Instagram',preview:'Quais documentos preciso?',messages:[{id:5,from:'client',text:'Quais documentos preciso?',time:'Ontem'}]}];

export default function Home(){
 const [view,setView]=useState('Dashboard'),[dark,setDark]=useState(false),[q,setQ]=useState(''),[toast,setToast]=useState('');
 const [leads,setLeads]=useState<Lead[]>(seedLeads),[convs,setConvs]=useState<Conv[]>(seedConvs),[selected,setSelected]=useState(1),[text,setText]=useState('');
 const [modal,setModal]=useState(false);
 useEffect(()=>{try{const l=localStorage.getItem('akdesk-leads');if(l)setLeads(JSON.parse(l));const c=localStorage.getItem('akdesk-convs');if(c)setConvs(JSON.parse(c))}catch{}},[]);
 useEffect(()=>{localStorage.setItem('akdesk-leads',JSON.stringify(leads))},[leads]);
 useEffect(()=>{localStorage.setItem('akdesk-convs',JSON.stringify(convs))},[convs]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2200);return()=>clearTimeout(t)}},[toast]);
 const filtered=useMemo(()=>leads.filter(x=>(x.name+' '+x.phone+' '+x.product).toLowerCase().includes(q.toLowerCase())),[leads,q]);
 const active=convs.find(x=>x.id===selected)||convs[0];
 const notify=(s:string)=>setToast(s);
 const send=()=>{if(!text.trim())return;setConvs(cs=>cs.map(c=>c.id===active.id?{...c,preview:text,messages:[...c.messages,{id:Date.now(),from:'agent',text:text.trim(),time:new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}]}:c));setText('');notify('Mensagem registrada em modo de teste')};
 const add=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setLeads(x=>[...x,{id:Date.now(),name:String(f.get('name')),phone:String(f.get('phone')),product:String(f.get('product')),stage:'Novo',owner:'Adriel',blocked:false}]);setModal(false);notify('Cliente criado em modo de teste')};
 return <div className={dark?'app dark':'app'}>
  <aside><div className="brand">A&K <em>Deskcomm</em></div><div className="org">SOLUÇÕES FINANCEIRAS</div>{nav.map(([i,n])=><button className={view===n?'nav active':'nav'} key={n} onClick={()=>setView(n)}><b>{i}</b>{n}</button>)}<button className="theme" onClick={()=>setDark(!dark)}>◐ {dark?'Modo claro':'Modo escuro'}</button></aside>
  <main><header><input value={q} onChange={e=>setQ(e.target.value)} placeholder="⌕ Buscar cliente, telefone ou conversa..."/><span className="online">● Operação online</span><div className="avatar">AM</div><div><b>Adriel Matos</b><small>Administrador</small></div></header>
  <section>{view==='Dashboard'&&<Dashboard leads={leads} go={setView}/>}
  {view==='Inbox'&&<Inbox convs={convs} active={active} selected={selected} select={setSelected} text={text} setText={setText} send={send}/>}
  {view==='Radar'&&<Radar leads={filtered} notify={notify}/>}
  {view==='Kanban'&&<Kanban leads={filtered} move={(id,s)=>{setLeads(x=>x.map(l=>l.id===id?{...l,stage:s}:l));notify('Etapa atualizada')}} add={()=>setModal(true)}/>}
  {view==='Clientes'&&<Clients leads={filtered} add={()=>setModal(true)} notify={notify}/>}
  {['Follow-ups','Automações','Respostas rápidas'].includes(view)&&<Simple title={view}/>}
  {view==='Ligações'&&<Calls notify={notify}/>}
  {view==='Campanhas'&&<Campaigns notify={notify}/>}
  {view==='Equipe'&&<Team notify={notify}/>}
  {view==='Auditoria'&&<Audit/>}
  {view==='Configurações'&&<Settings notify={notify}/>}
  </section></main>
  {modal&&<div className="modal"><form className="modalbox" onSubmit={add}><div className="title"><h2>Novo cliente</h2><button type="button" className="btn" onClick={()=>setModal(false)}>Fechar</button></div><label>Nome<input name="name" required/></label><label>Telefone<input name="phone" required/></label><label>Produto<select name="product"><option>INSS</option><option>CLT</option><option>SIAPE</option><option>FGTS</option><option>Benefício</option></select></label><button className="btn primary">Salvar</button></form></div>}
  {toast&&<div className="toast">✓ {toast}</div>}</div>
}

function Head({title,sub,action}:{title:string;sub:string;action?:React.ReactNode}){return <div className="title"><div><h1>{title}</h1><p>{sub}</p></div>{action&&<div>{action}</div>}</div>}
function Metric({a,b,c}:{a:string;b:string;c:string}){return <div className="card"><small>{a}</small><strong>{b}</strong><span>{c}</span></div>}
function Dashboard({leads,go}:{leads:Lead[];go:(v:string)=>void}){return <><Head title="Visão geral" sub="Central de atendimento da A&K Soluções Financeiras" action={<button className="btn primary" onClick={()=>go('Inbox')}>Abrir Inbox</button>}/><div className="metrics"><Metric a="Leads ativos" b={String(leads.filter(x=>!x.blocked).length)} c="Base operacional"/><Metric a="Conversas abertas" b="18" c="4 novas hoje"/><Metric a="Follow-ups" b="7" c="3 prioritários"/><Metric a="Conversão" b="14,8%" c="Indicador de demonstração"/></div><div className="cols"><div className="card"><h3>Atendimentos recentes</h3>{leads.slice(0,5).map(x=><div className="row" key={x.id}><div><b>{x.name}</b><small>{x.product} · {x.stage}</small></div><span className={x.blocked?'pill red':'pill'}>{x.blocked?'Bloqueado':'Aberto'}</span></div>)}</div><div className="card"><h3>Segurança da operação</h3><div className="row"><span>Isolamento da discadora</span><span className="pill green">Ativo</span></div><div className="row"><span>Auditoria</span><span className="pill">Preparada</span></div><div className="row"><span>Phone Link</span><span className="pill">Somente discadora</span></div><div className="notice">Dados desta versão são de demonstração local. Produção só após Auth/RLS e auditoria de segurança.</div></div></div></>}
function Inbox({convs,active,selected,select,text,setText,send}:{convs:Conv[];active:Conv;selected:number;select:(n:number)=>void;text:string;setText:(s:string)=>void;send:()=>void}){return <><Head title="Inbox" sub="Fila unificada de atendimento" action={<button className="btn">Filtros</button>}/><div className="inbox"><div className="list">{convs.map(c=><button className={selected===c.id?'conv active':'conv'} key={c.id} onClick={()=>select(c.id)}><b>{c.name}</b><small>{c.channel} · {c.preview}</small></button>)}</div><div className="chat"><div className="chathead"><b>{active.name}</b><small>{active.channel} · atendimento ativo</small></div><div className="messages">{active.messages.map(m=><div key={m.id} className={'bubble '+m.from}>{m.text}<small>{m.time}</small></div>)}</div><div className="composer"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Escreva uma mensagem de teste..."/><button className="btn primary" onClick={send}>Enviar</button></div></div><div className="detail"><h3>Customer 360</h3><div className="bigavatar">{active.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><b>{active.name}</b><small>Cliente ativo</small><hr/><small>Telefone</small><b>(79) 99911-2233</b><small>Tags</small><div><span className="tag">Lead</span><span className="tag">A&K</span></div></div></div></>}
function Radar({leads,notify}:{leads:Lead[];notify:(s:string)=>void}){return <><Head title="Radar" sub="Prioridades e clientes que pedem ação"/><div className="metrics"><Metric a="Alta prioridade" b="6" c="2 aguardando resposta"/><Metric a="Sem contato" b={String(leads.filter(x=>x.stage==='Novo').length)} c="Primeira abordagem"/><Metric a="Propostas" b={String(leads.filter(x=>x.stage==='Proposta').length)} c="Em acompanhamento"/><Metric a="Bloqueados" b={String(leads.filter(x=>x.blocked).length)} c="NPD/Não ligar"/></div><div className="card"><h3>Fila priorizada</h3>{leads.map(l=><div className="row" key={l.id}><div><b>{l.name}</b><small>{l.phone} · {l.product} · {l.stage}</small></div><button disabled={l.blocked} className="btn primary" onClick={()=>notify('Atendimento aberto para '+l.name)}>{l.blocked?'Bloqueado':'Atender'}</button></div>)}</div></>}
function Kanban({leads,move,add}:{leads:Lead[];move:(id:number,s:string)=>void;add:()=>void}){return <><Head title="Kanban" sub="Pipeline comercial" action={<button className="btn primary" onClick={add}>+ Novo lead</button>}/><div className="kanban">{stages.map(s=><div className="column" key={s}><h3>{s}<span>{leads.filter(l=>l.stage===s).length}</span></h3>{leads.filter(l=>l.stage===s).map(l=><div className="lead" key={l.id}><b>{l.name}</b><small>{l.phone}</small><span className="tag">{l.product}</span><select value={l.stage} onChange={e=>move(l.id,e.target.value)}>{stages.map(x=><option key={x}>{x}</option>)}</select></div>)}</div>)}</div></>}
function Clients({leads,add,notify}:{leads:Lead[];add:()=>void;notify:(s:string)=>void}){return <><Head title="Clientes" sub="Base de clientes e leads" action={<><button className="btn" onClick={()=>notify('Importador CSV/XLSX será conectado ao banco na etapa de produção')}>Importar</button><button className="btn primary" onClick={add}>+ Novo cliente</button></>}/><div className="card tablewrap"><table><thead><tr><th>Cliente</th><th>Telefone</th><th>Produto</th><th>Etapa</th><th>Responsável</th><th>Status</th></tr></thead><tbody>{leads.map(l=><tr key={l.id}><td><b>{l.name}</b></td><td>{l.phone}</td><td>{l.product}</td><td>{l.stage}</td><td>{l.owner}</td><td><span className={l.blocked?'pill red':'pill green'}>{l.blocked?'Não ligar':'Ativo'}</span></td></tr>)}</tbody></table></div></>}
function Simple({title}:{title:string}){const items=title==='Follow-ups'?['Maria Oliveira · Retornar hoje 10:30','João Santos · Enviar documentação 11:15','Ana Souza · Confirmar proposta 14:00']:title==='Automações'?['Novo lead → atribuir operador','Cliente respondeu → criar follow-up','24h sem contato → gerar retorno','STOP/NPD → bloquear abordagem']:['Boas-vindas','Simulação','Documentos','Retorno'];return <><Head title={title} sub="Módulo preparado para persistência e regras de produção" action={<button className="btn primary">+ Novo</button>}/><div className="card">{items.map((x,i)=><div className="row" key={x}><div><b>{x.split(' · ')[0]}</b><small>{x.includes(' · ')?x.split(' · ')[1]:'Regra configurada'}</small></div><span className="pill green">{i?'Ativo':'Prioridade'}</span></div>)}</div></>}
function Calls({notify}:{notify:(s:string)=>void}){return <><Head title="Ligações" sub="Discador interno somente para teste, separado do Phone Link" action={<button className="btn primary" onClick={()=>notify('Chamada simulada iniciada')}>Iniciar teste</button>}/><div className="card tablewrap"><table><thead><tr><th>Cliente</th><th>Número</th><th>Resultado</th><th>Duração</th><th>Operador</th></tr></thead><tbody>{[['Maria Oliveira','(79) 99911-2233','Atendeu','03:42','Adriel'],['João Santos','(79) 98877-1144','Retornar','01:18','Camila'],['Ana Souza','(79) 99771-6655','Não atendeu','00:00','Adriel']].map(r=><tr key={r[0]}>{r.map(c=><td key={c}>{c}</td>)}</tr>)}</tbody></table></div></>}
function Campaigns({notify}:{notify:(s:string)=>void}){return <><Head title="Campanhas" sub="Ações comerciais e distribuição" action={<button className="btn primary" onClick={()=>notify('Campanha criada em rascunho')}>+ Nova campanha</button>}/><div className="metrics"><Metric a="Ativas" b="3" c="Em execução"/><Metric a="Leads" b="1.284" c="Semana"/><Metric a="Contatos" b="742" c="57,8% da base"/><Metric a="Conversões" b="190" c="25,6%"/></div></>}
function Team({notify}:{notify:(s:string)=>void}){return <><Head title="Equipe" sub="Usuários, papéis e filas" action={<button className="btn primary" onClick={()=>notify('Convite preparado')}>+ Convidar</button>}/><div className="card tablewrap"><table><thead><tr><th>Usuário</th><th>Função</th><th>Status</th><th>Fila</th></tr></thead><tbody>{[['Adriel Matos','Administrador','Online','Principal'],['Camila Silva','Operador','Online','Principal'],['Rafael Santos','Operador','Ausente','Retornos']].map(r=><tr key={r[0]}>{r.map(c=><td key={c}>{c}</td>)}</tr>)}</tbody></table></div></>}
function Audit(){return <><Head title="Auditoria" sub="A trilha real será gravada no Supabase; estes eventos são apenas demonstração"/><div className="card tablewrap"><table><thead><tr><th>Data</th><th>Usuário</th><th>Ação</th><th>Recurso</th><th>Resultado</th></tr></thead><tbody>{[['Hoje 08:45','Adriel','lead.stage.update','lead:1032','Sucesso'],['Hoje 08:42','Adriel','conversation.message','conversation:1','Sucesso'],['Hoje 08:40','Camila','lead.assign','lead:1033','Sucesso']].map(r=><tr key={r.join('-')}>{r.map(c=><td key={c}>{c}</td>)}</tr>)}</tbody></table></div></>}
function Settings({notify}:{notify:(s:string)=>void}){return <><Head title="Configurações" sub="Segurança, organização e futura integração"/><div className="cols"><div className="card"><h3>Organização</h3><label>Nome<input defaultValue="A&K Soluções Financeiras"/></label><label>Fuso<select defaultValue="America/Sao_Paulo"><option>America/Sao_Paulo</option></select></label><button className="btn primary" onClick={()=>notify('Configurações salvas localmente')}>Salvar</button></div><div className="card"><h3>Integração com a discadora</h3><div className="row"><span>API autenticada</span><span className="pill">Desconectada</span></div><div className="row"><span>Webhooks</span><span className="pill">Preparados</span></div><div className="row"><span>Phone Link</span><span className="pill">Somente na discadora</span></div><div className="notice">Nenhuma chamada é enviada para o projeto da discadora nesta fase.</div></div></div></>}
